"""Utility module for visualizing the human visual gamut."""

from typing import Self


from ..gamut import GamutTraversalStep
from . import std_observer as std_observer


class Illuminant:
    """A standard illuminant."""
    def label(self) -> str: ...
    def is_empty(self) -> bool: ...
    def start(self) -> int: ...
    def end(self) -> int: ...
    def at(self, wavelength: int) -> float: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
    def __repr__(self) -> str: ...


class Observer:
    """A standard observer, that is, a color matching function."""
    def label(self) -> str: ...
    def is_empty(self) -> bool: ...
    def start(self) -> int: ...
    def end(self) -> int: ...
    def at(self, wavelength: int) -> list[float]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> list[float]: ...
    def __repr__(self) -> str: ...


class SpectrumTraversal:
    """An iterator over spectrum boundaries."""
    def __new__(cls, illuminant: Illuminant, observer: Observer) -> Self: ...
    def step_sizes(self) -> tuple[float, float]: ...
    def set_step_sizes(self, step_sizes: int) -> None: ...
    def white_point(self) -> list[float]: ...
    def restart(self) -> Self: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> GamutTraversalStep: ...
    def __repr__(self) -> str: ...


CIE_ILLUMINANT_D65: Illuminant
CIE_OBSERVER_2DEG_1931: Observer
CIE_OBSERVER_2DEG_2015: Observer
