name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  check:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"
        cache: "npm"
    - run: npm ci

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib maturin

    - name: Set up stable Rust
      run: rustup toolchain install stable

    - name: Check Rust code (with & without features)
      run: |
        cargo check
        cargo check --all-features

    - name: Run Clippy (with & without features)
      run: |
        cargo clippy
        cargo clippy --all-features

    - name: Check Rust format
      run: cargo fmt --check

    - name: Test Rust code
      run: cargo test

    - name: Build extension module
      run: pip install -e .

    - name: Typecheck and test Python code
      run: python -m runtest

